### ISSUE TITLE
It isn't working on Firefox

### ISSUE THREAD

**Issue by pedrokleiz** [milankragujevic/BrowserPopcorn#3]
It is not working on my Firefox 42.0b7 on Mac OS X 10.11.1 Beta (15B38b), if you need a list of extension, just ask me.
<img width="1680" alt="screen shot 2015-10-19 at 15 45 41" src="https://cloud.githubusercontent.com/assets/6828704/10589306/87da97b2-7678-11e5-86b6-968d934c44d3.png">

**Comment by milankragujevic** [comment]
Please try reloading the page, it often happens that the server gets overloaded and doesn't send data.

**Comment by milankragujevic** [comment]
Actually, no, there was an issue with the API server. I fixed it. It should be working now. Sorry about that...

**Comment by pedrokleiz** [comment]
Oh, it's working now. Thank you.
